# Generated by Django 4.2.16 on 2024-12-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='dashboard/profile/default2.png', upload_to='dashboard/profile/'),
        ),
    ]
