# Generated by Django 4.2.16 on 2024-12-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_commentmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(default='blog.jpg', upload_to='blog/'),
        ),
    ]
