# Generated by Django 4.2.16 on 2024-12-16 21:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_postmodel_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='content',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
