# Generated by Django 4.2.16 on 2024-12-16 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_postmodel_content_postmodel_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='body',
            new_name='content',
        ),
    ]
