# Generated by Django 4.2.16 on 2025-01-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_reviewmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='description',
            field=models.TextField(),
        ),
    ]
