# Generated by Django 4.2.16 on 2024-11-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='brief_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
