# Generated by Django 4.2.16 on 2024-11-07 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productmodel_brief_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='brief_description',
        ),
    ]
