# Generated by Django 4.2.16 on 2024-11-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_productmodel_brief_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='brief_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
