# Generated by Django 4.2.16 on 2025-01-06 21:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_wishlistmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistmodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlistmodel',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
