# Generated by Django 4.2.16 on 2025-01-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_productmodel_avg_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimagemodel',
            name='file',
            field=models.ImageField(upload_to='shop/extra-img/'),
        ),
    ]
