# Generated by Django 4.2.16 on 2025-01-10 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_productimagemodel_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimagemodel',
            old_name='Product',
            new_name='product',
        ),
    ]
